# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/FH_SQLModel',
                'doc_host': 'https://ndendic.github.io',
                'git_url': 'https://github.com/ndendic/FH_SQLModel',
                'lib_path': 'FH_SQLModel'},
  'syms': { 'FH_SQLModel.core': { 'FH_SQLModel.core.create_cell': ('core.html#create_cell', 'FH_SQLModel/core.py'),
                                  'FH_SQLModel.core.create_history_aware_prompt': ( 'core.html#create_history_aware_prompt',
                                                                                    'FH_SQLModel/core.py'),
                                  'FH_SQLModel.core.find_current_notebook': ('core.html#find_current_notebook', 'FH_SQLModel/core.py'),
                                  'FH_SQLModel.core.get_notebook_history': ('core.html#get_notebook_history', 'FH_SQLModel/core.py'),
                                  'FH_SQLModel.core.prompt': ('core.html#prompt', 'FH_SQLModel/core.py'),
                                  'FH_SQLModel.core.refresh_agent': ('core.html#refresh_agent', 'FH_SQLModel/core.py'),
                                  'FH_SQLModel.core.run_with_history': ('core.html#run_with_history', 'FH_SQLModel/core.py')}}}
