# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/FH_SQLModel',
                'doc_host': 'https://ndendic.github.io',
                'git_url': 'https://github.com/ndendic/FH_SQLModel',
                'lib_path': 'FH_SQLModel'},
  'syms': {'FH_SQLModel.core': {'FH_SQLModel.core.foo': ('core.html#foo', 'FH_SQLModel/core.py')}}}
